---
services:

  traefik:
    image: traefik:v3.2
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - type: bind
        source: "./traefik.yml"
        target: "/etc/traefik/dynamic_conf.yml"

  testy:
    image: lcrownover/testy
    build:
      ./app
    container_name: testy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.testy.rule=Host(`testy.localhost`)"
      - "traefik.http.routers.testy.entrypoints=web"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
