---
# http routing section
http:
  routers:
    to-testy:
      rule: "Host(`web.crownover.xyz`) && PathPrefix(`/testy/`)"
      service: testy
    to-whoami:
      rule: "Host(`web.crownover.xyz`) && PathPrefix(`/whoami/`)"
      service: whoami

  middlewares:
    http-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    # Define how to reach an existing service on our infrastructure
    whoami:
      loadBalancer:
        servers:
        - url: http://whoami
    testy:
      loadBalancer:
        servers:
          - url: http://testy:3001
